use crate::ffi::window::{self as ffi, EventType};

/// Defines a system event and its parameters.
///
/// `Event` holds all the informations about a system event that just happened.
///
/// Events are retrieved using the
/// [`Window::poll_event`] or [`Window::wait_event`] functions.
///
/// An `Event` instance contains the type of the event
/// (mouse moved, key pressed, window closed, ...) as well as the details about this
/// particular event.
///
/// [`Window::poll_event`]: crate::window::Window::poll_event
/// [`Window::wait_event`]: crate::window::Window::wait_event
///
#[derive(Clone, PartialEq, Debug, Copy)]
pub enum Event {
    /// The window requested to be closed
    Closed,
    /// The window was resized
    Resized {
        /// New size, in pixels
        size: ffi::sfVector2u,
    },
    /// The window lost the focus
    FocusLost,
    /// The window gained the focus
    FocusGained,
    /// A character was entered
    TextEntered {
        /// The character entered by the user
        unicode: char,
    },
    /// A key was pressed
    KeyPressed {
        /// The pressed key
        code: ffi::Key,
        /// The scancode of the pressed key
        scan: ffi::Scancode,
        /// Is alt pressed too?
        alt: bool,
        /// Is ctrl pressed too?
        ctrl: bool,
        /// Is shift pressed too?
        shift: bool,
        /// Is system pressed too?
        system: bool,
    },
    /// A key was released
    KeyReleased {
        /// The released key
        code: ffi::Key,
        /// The scancode of the released key
        scan: ffi::Scancode,
        /// Is alt released too?
        alt: bool,
        /// Is ctrl released too?
        ctrl: bool,
        /// Is shift released too?
        shift: bool,
        /// Is system released too?
        system: bool,
    },
    /// The mouse wheel was scrolled
    MouseWheelScrolled {
        /// Which wheel (for mice with multiple ones).
        wheel: ffi::MouseWheel,
        /// Wheel offset (positive is up/left, negative is down/right).
        /// High-precision mice may use non-integral offsets.
        delta: f32,
        /// Position of the mouse pointer, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// A mouse button was pressed
    MouseButtonPressed {
        /// Code of the button that has been pressed.
        button: ffi::MouseButton,
        /// Position of the mouse pointer, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// A mouse button was released
    MouseButtonReleased {
        /// Code of the button that has been pressed.
        button: ffi::MouseButton,
        /// Position of the mouse pointer, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// The mouse cursor moved
    MouseMoved {
        /// Position of the mouse pointer, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// Raw mouse input data comes unprocessed from the
    /// operating system hence "raw". While the `MouseMoved`
    /// position value is dependent on the screen resolution,
    /// raw data is not. If the physical mouse is moved too
    /// little to cause the screen cursor to move at least a
    /// single pixel, no `MouseMoved` event will be generated. In
    /// contrast, any movement information generated by the
    /// mouse independent of its sensor resolution will always
    /// generate a `MouseMovedRaw` event.
    ///
    /// In addition to screen resolution independence, raw
    /// mouse data also does not have mouse acceleration or
    /// smoothing applied to it as `MouseMoved` does.
    ///
    /// Raw mouse movement data is intended for controlling
    /// non-cursor movement, e.g. controlling the camera
    /// orientation in a first person view, whereas `MouseMoved`
    /// is intended primarily for controlling things related to
    /// the screen cursor hence the additional processing
    /// applied to it.
    ///
    /// Currently, raw mouse input events will only be generated
    /// on Windows and Linux.
    MouseMovedRaw {
        /// Delta movement of the mouse since the last event
        delta: ffi::sfVector2i,
    },
    /// The mouse cursor entered the area of the window
    MouseEntered,
    /// The mouse cursor left the area of the window
    MouseLeft,
    /// A joystick button was pressed
    JoystickButtonPressed {
        /// Index of the joystick (in range `0 .. `[`joystick::COUNT`]` - 1`)
        ///
        /// [`joystick::COUNT`]: crate::window::joystick::COUNT
        joystickid: u32,
        /// Index of the button that has been pressed (in range `0 .. `[`joystick::BUTTON_COUNT`]` - 1`)
        ///
        /// [`joystick::BUTTON_COUNT`]: crate::window::joystick::BUTTON_COUNT
        button: u32,
    },
    /// A joystick button was released
    JoystickButtonReleased {
        /// Index of the joystick (in range `0 .. `[`joystick::COUNT`]` - 1`)
        ///
        /// [`joystick::COUNT`]: crate::window::joystick::COUNT
        joystickid: u32,
        /// Index of the button that has been pressed (in range `0 .. `[`joystick::BUTTON_COUNT`]` - 1`)
        ///
        /// [`joystick::BUTTON_COUNT`]: crate::window::joystick::BUTTON_COUNT
        button: u32,
    },
    /// The joystick moved along an axis
    JoystickMoved {
        /// Index of the joystick (in range `0 .. `[`joystick::COUNT`]` - 1`)
        ///
        /// [`joystick::COUNT`]: crate::window::joystick::COUNT
        joystickid: u32,
        /// Axis on which the joystick moved.
        axis: crate::window::joystick::Axis,
        /// New position on the axis (in range [-100 .. 100])
        position: f32,
    },
    /// A joystick was connected
    JoystickConnected {
        /// Index of the joystick (in range `0 .. `[`joystick::COUNT`]` - 1`)
        ///
        /// [`joystick::COUNT`]: crate::window::joystick::COUNT
        joystickid: u32,
    },
    /// A joystick was disconnected
    JoystickDisconnected {
        /// Index of the joystick (in range `0 .. `[`joystick::COUNT`]` - 1`)
        ///
        /// [`joystick::COUNT`]: crate::window::joystick::COUNT
        joystickid: u32,
    },
    /// A touch event began
    TouchBegan {
        /// Index of the finger in case of multi-touch events.
        finger: u32,
        /// Start position of the touch, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// A touch moved
    TouchMoved {
        /// Index of the finger in case of multi-touch events.
        finger: u32,
        /// Start position of the touch, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// A touch event ended
    TouchEnded {
        /// Index of the finger in case of multi-touch events.
        finger: u32,
        /// Start position of the touch, relative to the top left of the owner window
        position: ffi::sfVector2i,
    },
    /// A sensor value changed
    SensorChanged {
        /// Type of the sensor.
        type_: ffi::window::sfSensorType,
        /// Current value of the sensor on the X, Y, and Z axes
        value: ffi::sfVector3f,
    },
}

impl Event {
    pub(crate) unsafe fn from_raw(event: &ffi::Event) -> Option<Self> {
        use crate::window::Event::{Closed, Resized, FocusLost, FocusGained, TextEntered, KeyPressed, KeyReleased, MouseWheelScrolled, MouseButtonPressed, MouseButtonReleased, MouseMoved, MouseMovedRaw, MouseEntered, MouseLeft, JoystickButtonPressed, JoystickButtonReleased, JoystickMoved, JoystickConnected, JoystickDisconnected, TouchBegan, TouchMoved, TouchEnded, SensorChanged};
        let evt = match event.type_ {
            EventType::Closed => Closed,
            EventType::Resized => Resized {
                size: unsafe { event.union.size.size },
            },
            EventType::FocusLost => FocusLost,
            EventType::FocusGained => FocusGained,
            EventType::TextEntered => TextEntered {
                unicode: std::char::from_u32(unsafe { event.union.text.unicode })
                    .expect("Invalid unicode encountered on TextEntered event"),
            },
            EventType::KeyPressed => KeyPressed {
                code: unsafe { event.union.key.code },
                scan: unsafe { event.union.key.scan },
                alt: unsafe { event.union.key.alt },
                ctrl: unsafe { event.union.key.control },
                shift: unsafe { event.union.key.shift },
                system: unsafe { event.union.key.system },
            },
            EventType::KeyReleased => KeyReleased {
                code: unsafe { event.union.key.code },
                scan: unsafe { event.union.key.scan },
                alt: unsafe { event.union.key.alt },
                ctrl: unsafe { event.union.key.control },
                shift: unsafe { event.union.key.shift },
                system: unsafe { event.union.key.system },
            },
            EventType::MouseWheelScrolled => MouseWheelScrolled {
                wheel: unsafe { event.union.mouse_wheel_scroll.wheel },
                delta: unsafe { event.union.mouse_wheel_scroll.delta },
                position: unsafe { event.union.mouse_wheel_scroll.position },
            },
            EventType::MouseButtonPressed => MouseButtonPressed {
                button: unsafe { event.union.mouse_button.button },
                position: unsafe { event.union.mouse_button.position },
            },
            EventType::MouseButtonReleased => MouseButtonReleased {
                button: unsafe { event.union.mouse_button.button },
                position: unsafe { event.union.mouse_button.position },
            },
            EventType::MouseMoved => MouseMoved {
                position: unsafe { event.union.mouse_button.position },
            },
            EventType::MouseMovedRaw => MouseMovedRaw {
                delta: unsafe { event.union.mouse_move_raw.delta },
            },
            EventType::MouseEntered => MouseEntered,
            EventType::MouseLeft => MouseLeft,
            EventType::JoystickButtonPressed => JoystickButtonPressed {
                joystickid: unsafe { event.union.joystick_button.joystick_id },
                button: unsafe { event.union.joystick_button.button },
            },
            EventType::JoystickButtonReleased => JoystickButtonReleased {
                joystickid: unsafe { event.union.joystick_button.joystick_id },
                button: unsafe { event.union.joystick_button.button },
            },
            EventType::JoystickMoved => JoystickMoved {
                joystickid: unsafe { event.union.joystick_move.joystick_id },
                axis: unsafe { event.union.joystick_move.axis },
                position: unsafe { event.union.joystick_move.position },
            },
            EventType::JoystickConnected => JoystickConnected {
                joystickid: unsafe { event.union.joystick_connect.joystick_id },
            },
            EventType::JoystickDisconnected => JoystickDisconnected {
                joystickid: unsafe { event.union.joystick_connect.joystick_id },
            },
            EventType::TouchBegan => TouchBegan {
                finger: unsafe { event.union.touch.finger },
                position: unsafe { event.union.mouse_button.position },
            },
            EventType::TouchMoved => TouchMoved {
                finger: unsafe { event.union.touch.finger },
                position: unsafe { event.union.mouse_button.position },
            },
            EventType::TouchEnded => TouchEnded {
                finger: unsafe { event.union.touch.finger },
                position: unsafe { event.union.mouse_button.position },
            },
            EventType::SensorChanged => SensorChanged {
                type_: unsafe { event.union.sensor.type_ },
                value: unsafe { event.union.sensor.value },
            },
        };
        Some(evt)
    }
}
